indicator: submit
elements:
    - type: Text
      name: task
      label: Task
      attributes:
          title: Enter a task title here
      constraints:
        - type: Length
          min: 5
          max: 100
          message: must be between 5 and 100 characters long
        - Required

    - type: Text
      name: comment
      label: Description
      attributes:
        title: Enter a full description for the required task
 
    - type: Select
      name: assigned_to
      label: AssignedTo
 
    - type: Submit
      name: submit 
      value: Submit
filter:
    - TrimEdges
    - HTMLEscape
